(function () {
    'use strict';
    var initialExtent = [15685226.741739, 4613114.098135, 15692580.637673, 4617549.007290];
    var panels = [
        '<section id="layers-panel" class="site-panel" hidden aria-label="レイヤー設定"><button class="panel-close" type="button" aria-label="閉じる">×</button><h2>背景・レイヤー</h2><label class="layer-option"><input type="checkbox" data-layer="koaza" checked> 小字界・小字名</label><label class="layer-option"><input type="checkbox" data-layer="oaza" checked> 大字界</label><label class="opacity-control background-opacity">背景地図の濃さ <input type="range" min="0" max="100" value="100" aria-label="背景地図の濃さ"></label><button class="map-home" type="button">仙台の表示範囲へ戻る</button></section>',
        '<section id="legend-panel" class="site-panel" hidden aria-label="凡例"><button class="panel-close" type="button" aria-label="閉じる">×</button><h2>凡例</h2><h3>小字</h3><div class="legend-row"><img src="styles/legend/sendaikoazamap_1_0.png" alt="">仙台</div><div class="legend-row"><img src="styles/legend/sendaikoazamap_1_1.png" alt="">南小泉</div><div class="legend-row"><img src="styles/legend/sendaikoazamap_1_2.png" alt="">蒲町</div><div class="legend-row"><img src="styles/legend/sendaikoazamap_1_3.png" alt="">伊在</div><div class="legend-row"><img src="styles/legend/sendaikoazamap_1_4.png" alt="">六丁目</div><h3>大字</h3><div class="legend-row"><img src="styles/legend/sendaioazamap_2.png" alt="">大字界</div></section>',
        '<section id="about-panel" class="site-panel" hidden aria-label="この地図について"><button class="panel-close" type="button" aria-label="閉じる">×</button><h2>この地図について</h2><p>仙台市域の小字・大字を閲覧するための地図です。地図上の範囲をクリックすると、属性情報を確認できます。</p><p>境界や名称は資料に基づく参考情報です。権利関係・行政手続きなどの正式な確認には利用しないでください。</p><p>背景地図：<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">国土地理院タイル</a></p><p>更新日・データ出典は、確認後にこの欄へ追記できます。</p></section>'
    ];
    document.body.insertAdjacentHTML('beforeend', panels.join(''));
    document.body.insertAdjacentHTML('beforeend', '<output id="zoom-status" aria-label="現在のズーム値">z 0.0</output>');
    document.querySelector('#layers-panel h2').insertAdjacentHTML('afterend', '<label class="basemap-control">背景地図<select aria-label="背景地図を選択"><option value="pale">淡色地図</option><option value="std">標準地図</option><option value="ort">最新写真</option><option value="photo2008">2008年写真</option><option value="gazo3">1984年写真</option><option value="gazo1">1974年写真</option><option value="old10">1961年写真</option><option value="usa10">1945年写真</option></select></label>');
    function closePanels() { document.querySelectorAll('.site-panel').forEach(function (panel) { panel.hidden = true; }); document.querySelectorAll('[data-panel-target]').forEach(function (button) { button.setAttribute('aria-expanded', 'false'); }); }
    document.querySelectorAll('[data-panel-target]').forEach(function (button) { button.setAttribute('aria-expanded', 'false'); button.addEventListener('click', function () { var panel = document.getElementById(button.dataset.panelTarget); var open = panel.hidden; closePanels(); panel.hidden = !open; button.setAttribute('aria-expanded', String(open)); }); });
    document.querySelectorAll('.panel-close').forEach(function (button) { button.addEventListener('click', closePanels); });
    var layerByKey = { koaza: lyr_sendaikoazamap_1, oaza: lyr_sendaioazamap_2 };
    var basemaps = { pale: { url: 'https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png', minZoom: 5, maxZoom: 18 }, std: { url: 'https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png', minZoom: 5, maxZoom: 18 }, ort: { url: 'https://cyberjapandata.gsi.go.jp/xyz/ort/{z}/{x}/{y}.jpg', minZoom: 14, maxZoom: 18 }, photo2008: { url: 'https://cyberjapandata.gsi.go.jp/xyz/nendophoto2008/{z}/{x}/{y}.png', minZoom: 14, maxZoom: 18 }, gazo3: { url: 'https://cyberjapandata.gsi.go.jp/xyz/gazo3/{z}/{x}/{y}.jpg', minZoom: 10, maxZoom: 17 }, gazo1: { url: 'https://cyberjapandata.gsi.go.jp/xyz/gazo1/{z}/{x}/{y}.jpg', minZoom: 10, maxZoom: 17 }, old10: { url: 'https://cyberjapandata.gsi.go.jp/xyz/ort_old10/{z}/{x}/{y}.png', minZoom: 10, maxZoom: 17 }, usa10: { url: 'https://cyberjapandata.gsi.go.jp/xyz/ort_USA10/{z}/{x}/{y}.png', minZoom: 10, maxZoom: 17 } };
    document.querySelector('.basemap-control select').addEventListener('change', function (event) { var selected = basemaps[event.target.value]; lyr__0.setSource(new ol.source.XYZ({ url: selected.url, minZoom: selected.minZoom, maxZoom: selected.maxZoom, attributions: '地理院タイル' })); });
    var polygonOpacityControl = document.querySelector('.opacity-control');
    polygonOpacityControl.insertAdjacentHTML('beforebegin', '<label class="opacity-control">小字ポリゴンの濃さ <input class="polygon-opacity" type="range" min="0" max="100" value="30" aria-label="小字ポリゴンの濃さ"></label>');
    document.querySelector('.polygon-opacity').addEventListener('input', function (event) { koazaPolygonOpacity = Number(event.target.value) / 100; lyr_sendaikoazamap_1.changed(); });
    var zoomStatus = document.getElementById('zoom-status');
    function updateZoomStatus() { zoomStatus.textContent = 'z ' + map.getView().getZoom().toFixed(1); }
    map.on('moveend', updateZoomStatus);
    updateZoomStatus();
    window.addEventListener('resize', function () { lyr_sendaikoazamap_1.changed(); });
    document.querySelectorAll('[data-layer]').forEach(function (input) { input.addEventListener('change', function () { layerByKey[input.dataset.layer].setVisible(input.checked); }); });
    document.querySelector('.background-opacity input').addEventListener('input', function (event) { lyr__0.setOpacity(Number(event.target.value) / 100); });
    document.querySelector('.map-home').addEventListener('click', function () { map.getView().fit(initialExtent, { size: map.getSize(), duration: 350, padding: [82, 20, 20, 20] }); closePanels(); });
}());
